### PR TITLE
Update a little.

### PR DESCRIPTION
**Pull request by Pitometsu**

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
These changes look really useful - Id be happy to merge, although you have conflicts?

**Comment by Pitometsu** [comment]
Yep, looks like you updated Podfile recently. I'll try to push merge commit as well.

**Comment by Pitometsu** [comment]
@ColinEberhardt thank you for feedback. Note change: new tag `1.1` in `podspec`; I left making tag and pushing new `podspec` to `cocoapods` up to your decision. Thank you for review.

**Comment by Pitometsu** [comment]
@Loadex thank you for your commits 👍

**Comment by ColinEberhardt** [comment]
Thank you - much appreciated :-)

**Comment by Pitometsu** [comment]
Thank you for review and accepting commits!

**Pull request merged**
