### PR TITLE
Fixed typo if respond to selector causing bad forwarding

### PR DESCRIPTION
**Pull request by thibault-carpentier**
Oops i left a typo in the check of a forwarding. Sorry about that

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Ah, thanks for the update, I didn't spot that either!

Are you using the cocoa pod now?

**Comment by thibault-carpentier** [comment]
Yeah this PR is long and boring to review, and typo like this one aren't easy to spot ! 
For now i was using it but with the source set to my repo, gonna update this during the day !

**Comment by thibault-carpentier** [comment]
I wish there was an other way to forward for delegates instead of just rewrite the entire implementation ! And with this method, if we want to also give to the user some of the datasources forwarding we will encounter a problem : 
In UITableView, if you implement `titleForRowInSection` the method `viewForHeaderInSection` won't be called. Any idea how to achieve this for later ?

**Comment by thibault-carpentier** [comment]
Maybe this way of forwarding isn't the correct way ?

**Pull request merged**
